version: '3.8'

networks:
  glitchtip_network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust' # Consider removing this and setting a password
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - glitchtip_network

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - glitchtip_network

  web:
    image: glitchtip/glitchtip
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
    networks:
      - glitchtip_network

  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
    networks:
      - glitchtip_network

  migrate:
    image: glitchtip/glitchtip
    command: './manage.py migrate'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - glitchtip_network

volumes:
  pg-data:
  uploads:
