version: '3'

networks:
  petpot_network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - petpot_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - petpot_network

  admin:
    build:
      context: .
      dockerfile: ./Dockerfile.admin
    env_file:
      - .env
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 4050:4050
    networks:
      - petpot_network

  booking:
    build:
      context: .
      dockerfile: ./Dockerfile.booking
    env_file:
      - .env
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 4070:4070
    networks:
      - petpot_network

  petpot:
    build:
      context: .
      dockerfile: ./Dockerfile.petpot
    env_file:
      - .env
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 4030:4030
    networks:
      - petpot_network
