version: '3.8'

networks:
  petpot_network:
    driver: bridge

services:
  admin:
    build:
      context: .
      dockerfile: ./Dockerfile.admin
    env_file:
      - .env
    ports:
      - 4050:4050
    networks:
      - petpot_network

  booking:
    build:
      context: .
      dockerfile: ./Dockerfile.booking
    env_file:
      - .env
    ports:
      - 4070:4070
    networks:
      - petpot_network

  petpot:
    build:
      context: .
      dockerfile: ./Dockerfile.petpot
    env_file:
      - .env
    ports:
      - 4030:4030
    networks:
      - petpot_network
