version: '3'

x-environment: &default-environment
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  SECRET_KEY: 544a00ec69e1d877a5abd23580bdbdc06ca686e5fc1f52062c036320b0288a06 # best to run openssl rand -hex 32
  PORT: 8000
  EMAIL_URL: consolemail:// # Example smtp://email:password@smtp_url:port https://glitchtip.com/documentation/install#configuration
  GLITCHTIP_DOMAIN: https://cenbot.click/glitchtip # Change this to your domain
  DEFAULT_FROM_EMAIL: quanva2521@gmail.com # Change this to your email
  CELERY_WORKER_AUTOSCALE: '1,3' # Scale between 1 and 3 to prevent excessive memory usage. Change it or remove to set it to the number of cpu cores.
  CELERY_WORKER_MAX_TASKS_PER_CHILD: '10000'

x-depends_on: &default-depends_on
  - postgres
  - redis

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - petpot_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - petpot_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust' # Consider removing this and setting a password
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped
  web:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    ports:
      - '8000:8000'
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  migrate:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    command: './manage.py migrate'
    environment: *default-environment

  admin:
    build:
      context: .
      dockerfile: ./Dockerfile.admin
    env_file:
      - .env
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 4050:4050
    networks:
      - petpot_network

  booking:
    build:
      context: .
      dockerfile: ./Dockerfile.booking
    env_file:
      - .env
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 4070:4070
    networks:
      - petpot_network

  petpot:
    build:
      context: .
      dockerfile: ./Dockerfile.petpot
    env_file:
      - .env
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 4030:4030
    networks:
      - petpot_network

networks:
  petpot_network:
    driver: bridge

volumes:
  pg-data:
  uploads:
