export const SERVICE_NAME = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  BOOKING_SERVICE: 'BOOKING_SERVICE',
  PETPOT_SERVICE: 'PETPOT_SERVICE',
};

export const SERVICE_PATTERN = {
  AUTHENTICATION: 'AUTHENTICATION',
};
